# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import scribble_pb2 as scribble__pb2


class TextToImageStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.convert = channel.unary_unary(
        '/scribble.TextToImage/convert',
        request_serializer=scribble__pb2.ImageSpec.SerializeToString,
        response_deserializer=scribble__pb2.Image.FromString,
        )


class TextToImageServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def convert(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TextToImageServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'convert': grpc.unary_unary_rpc_method_handler(
          servicer.convert,
          request_deserializer=scribble__pb2.ImageSpec.FromString,
          response_serializer=scribble__pb2.Image.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'scribble.TextToImage', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
