# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scribble.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='scribble.proto',
  package='scribble',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0escribble.proto\x12\x08scribble\"<\n\tImageSpec\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08\x66ontsize\x18\x02 \x01(\x05\x12\x0f\n\x07imgsize\x18\x03 \x01(\x05\"\x16\n\x05Image\x12\r\n\x05Image\x18\x01 \x01(\x0c\x32@\n\x0bTextToImage\x12\x31\n\x07\x63onvert\x12\x13.scribble.ImageSpec\x1a\x0f.scribble.Image\"\x00\x62\x06proto3')
)




_IMAGESPEC = _descriptor.Descriptor(
  name='ImageSpec',
  full_name='scribble.ImageSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='scribble.ImageSpec.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fontsize', full_name='scribble.ImageSpec.fontsize', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imgsize', full_name='scribble.ImageSpec.imgsize', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=88,
)


_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='scribble.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Image', full_name='scribble.Image.Image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=112,
)

DESCRIPTOR.message_types_by_name['ImageSpec'] = _IMAGESPEC
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageSpec = _reflection.GeneratedProtocolMessageType('ImageSpec', (_message.Message,), dict(
  DESCRIPTOR = _IMAGESPEC,
  __module__ = 'scribble_pb2'
  # @@protoc_insertion_point(class_scope:scribble.ImageSpec)
  ))
_sym_db.RegisterMessage(ImageSpec)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), dict(
  DESCRIPTOR = _IMAGE,
  __module__ = 'scribble_pb2'
  # @@protoc_insertion_point(class_scope:scribble.Image)
  ))
_sym_db.RegisterMessage(Image)



_TEXTTOIMAGE = _descriptor.ServiceDescriptor(
  name='TextToImage',
  full_name='scribble.TextToImage',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=114,
  serialized_end=178,
  methods=[
  _descriptor.MethodDescriptor(
    name='convert',
    full_name='scribble.TextToImage.convert',
    index=0,
    containing_service=None,
    input_type=_IMAGESPEC,
    output_type=_IMAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TEXTTOIMAGE)

DESCRIPTOR.services_by_name['TextToImage'] = _TEXTTOIMAGE

# @@protoc_insertion_point(module_scope)
