winbuild:
	GOOS=windows go build -o scribble.exe "github.com/utsavanand2/scribble-diary/scribble-cli/cmd/go-cli"

osxbuild:
	GOOS=darwin go build -o scribble.exe "github.com/utsavanand2/scribble-diary/scribble-cli/cmd/go-cli"

build:
	GOOS=linux go build -o scribble "github.com/utsavanand2/scribble-diary/scribble-cli/cmd/go-cli"